# Generated by Django 2.0.2 on 2018-03-04 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=800)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=8000)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(default=django.utils.timezone.now)),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
                ('modification_date', models.DateField(default=django.utils.timezone.now)),
                ('fk_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('fk_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Priority')),
                ('fk_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Status')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='fk_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
