# Generated by Django 2.0.2 on 2018-03-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180304_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ending_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fk_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fk_priority',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fk_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Status'),
        ),
    ]
