# Generated by Django 2.0.2 on 2018-03-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180323_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fk_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.Task'),
        ),
    ]
