# Generated by Django 2.0.2 on 2018-03-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180323_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fk_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
